import { Geist, Geist_Mono,Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./sections/Footer";
import { ModalProvider } from './Contexts/ModalContext';
import ProductModal from './components/ProductModal';


const openSans = Plus_Jakarta_Sans({
  variable: "--font-sans",
  subsets: ["latin"],

});

export const metadata = {
  title: "Impressive Cabinets ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${openSans.variable} antialiased`}
      >
        <ModalProvider>
        <Navbar />
        {children}
        <Footer />
        <ProductModal />
        </ModalProvider>
      </body>
    </html>
  );
}
